version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm config set "//registry.yarnpkg.com/:_authToken" $NPM_AUTH
      - run: npm publish --access public
    tags:
      only: /^v?[0-9]+(\.[0-9]+)*(-.+)?/
