version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/react-prism
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint